version: '3.9'

services:
  psql:
    image: postgres:latest
    container_name: postgresdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0809"
      # PGDATA: /data/postgres
      # POSTGRES_DB: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data \
    command: postgres -c 'max_connections=500'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -p 5432 -U postgres -d postgres" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  app1:
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: be-boiler
    depends_on:
      - psql
    networks:
      - my_network
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - psql # Ensures pgAdmin starts after PostgreSQL
  #   networks:
  #     - my_network

  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - my_network
    environment:
      DISABLE_IPV6: 'true'

networks:
  my_network:
    driver: bridge
