version: '3.9'
services:
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0809
    ports:
      - '5433:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data \
    command: postgres -c 'max_connections=500'
    networks:
      - my_network
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - my_network
    volumes:
      - pgadmin4_container_vol:/var/lib/pgadmin

networks:
    my_network:
        name: my_network
        driver: bridge

volumes:
  pgadmin4_container_vol:
